name: Build Flutter App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Flutter doctor (diagnostic info)
      run: flutter doctor -v
    
    - name: Analyze code
      run: flutter analyze --no-fatal-infos
      continue-on-error: true
    
    - name: Run tests (if test directory exists)
      run: |
        if [ -d "test" ]; then
          flutter test
        else
          echo "No test directory found, skipping tests"
        fi
      continue-on-error: true
    
    - name: Build APK
      run: |
        echo "Building APK..."
        echo "Temporarily modifying build.gradle for CI..."
        # Backup original file
        cp android/build.gradle android/build.gradle.bak
        # Add mavenCentral() at the start of allprojects repositories
        sed -i '/repositories {/a\        mavenCentral()' android/build.gradle
        echo "Modified build.gradle for CI"
        echo "Updated repositories:"
        grep -A 5 "allprojects" android/build.gradle
        flutter build apk --release --verbose 2>&1 | tee build.log
        exit_code=${PIPESTATUS[0]}
        if [ $exit_code -ne 0 ]; then
          echo "Build failed with exit code: $exit_code"
          echo "Last 100 lines of build log:"
          tail -100 build.log
          echo "Searching for error messages:"
          grep -i "error\|exception\|failed" build.log | tail -20
          exit $exit_code
        fi
        echo "APK build completed. Checking outputs:"
        find build/app/outputs -name "*.apk" -type f | head -5
      env:
        FLUTTER_GRADLE_PLUGIN_APPLY_MODE: legacy
        GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
        GRADLE_OPTS: -Xmx4096m -Dfile.encoding=UTF-8
    
    - name: Build App Bundle
      run: |
        echo "Building App Bundle..."
        flutter build appbundle --release --verbose
        echo "AAB build completed. Checking outputs:"
        find build/app/outputs -name "*.aab" -type f | head -5
      env:
        FLUTTER_GRADLE_PLUGIN_APPLY_MODE: legacy
        GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
        GRADLE_OPTS: -Xmx4096m -Dfile.encoding=UTF-8
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Flutter doctor (diagnostic info)
      run: flutter doctor -v
    
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
    
    - name: Build iOS (no signing)
      run: |
        echo "Building iOS app..."
        flutter build ios --release --no-codesign --verbose
        echo "iOS build completed. Checking outputs:"
        ls -la build/ios/iphoneos/ || echo "Build directory not found"
    
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r app-release.ipa Payload/
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: build/ios/iphoneos/app-release.ipa

  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Flutter doctor (diagnostic info)
      run: flutter doctor -v
    
    - name: Build Web
      run: flutter build web --release
    
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/