name: Release Build

on:
  release:
    types: [ published ]

jobs:
  release-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Fix Maven repositories for CI
      run: |
        echo "Temporarily replacing Maven repositories for CI environment..."
        # Backup original files
        cp android/build.gradle android/build.gradle.bak
        # Comment out Aliyun mirrors and add official repositories
        sed -i 's|maven { url '\''https://maven.aliyun.com/repository/google'\'' }|google()\n        mavenCentral()\n        maven { url "https://jitpack.io" }\n        // maven { url "https://maven.aliyun.com/repository/google" }|g' android/build.gradle
        sed -i 's|maven { url '\''https://maven.aliyun.com/repository/jcenter'\'' }|// maven { url "https://maven.aliyun.com/repository/jcenter" }|g' android/build.gradle
        sed -i 's|maven { url '\''https://maven.aliyun.com/repository/public'\'' }|// maven { url "https://maven.aliyun.com/repository/public" }|g' android/build.gradle
        echo "Repository configuration updated for CI"
        cat android/build.gradle | grep -A 5 -B 5 "repositories"
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Flutter doctor (diagnostic info)
      run: flutter doctor -v
    
    - name: Build APK
      run: flutter build apk --release
      env:
        FLUTTER_GRADLE_PLUGIN_APPLY_MODE: legacy
    
    - name: Build App Bundle
      run: flutter build appbundle --release
      env:
        FLUTTER_GRADLE_PLUGIN_APPLY_MODE: legacy
    
    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: freego-flutter-android-${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload AAB to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/app/outputs/bundle/release/app-release.aab
        asset_name: freego-flutter-android-${{ github.event.release.tag_name }}.aab
        asset_content_type: application/octet-stream

  release-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Flutter doctor (diagnostic info)
      run: flutter doctor -v
    
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
    
    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign
      env:
        FLUTTER_GRADLE_PLUGIN_APPLY_MODE: legacy
    
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r freego-flutter-ios-${{ github.event.release.tag_name }}.ipa Payload/
    
    - name: Upload IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/ios/iphoneos/freego-flutter-ios-${{ github.event.release.tag_name }}.ipa
        asset_name: freego-flutter-ios-${{ github.event.release.tag_name }}.ipa
        asset_content_type: application/octet-stream