name: Release Build

on:
  release:
    types: [ published ]

jobs:
  release-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Flutter doctor (diagnostic info)
      run: flutter doctor -v
    
    - name: Build APK
      run: flutter build apk --release
      env:
        FLUTTER_GRADLE_PLUGIN_APPLY_MODE: legacy
        GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
        GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m" -Dfile.encoding=UTF-8 -I${{ github.workspace }}/.github/ci-init.gradle
    
    - name: Build App Bundle
      run: flutter build appbundle --release
      env:
        FLUTTER_GRADLE_PLUGIN_APPLY_MODE: legacy
        GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
        GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m" -Dfile.encoding=UTF-8 -I${{ github.workspace }}/.github/ci-init.gradle
    
    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: freego-flutter-android-${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload AAB to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/app/outputs/bundle/release/app-release.aab
        asset_name: freego-flutter-android-${{ github.event.release.tag_name }}.aab
        asset_content_type: application/octet-stream

  release-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Flutter doctor (diagnostic info)
      run: flutter doctor -v
    
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
    
    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign
    
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r freego-flutter-ios-${{ github.event.release.tag_name }}.ipa Payload/
    
    - name: Upload IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/ios/iphoneos/freego-flutter-ios-${{ github.event.release.tag_name }}.ipa
        asset_name: freego-flutter-ios-${{ github.event.release.tag_name }}.ipa
        asset_content_type: application/octet-stream