name: Status Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  status-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.2'
        channel: 'stable'
        cache: true
    
    - name: Flutter doctor
      run: flutter doctor -v
    
    - name: Check project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo ""
        echo "=== Flutter Project Files ==="
        ls -la pubspec.yaml lib/ android/ ios/ || echo "Some directories missing"
        echo ""
        echo "=== GitHub Actions ==="
        ls -la .github/workflows/
    
    - name: Validate pubspec.yaml
      run: |
        echo "=== Validating pubspec.yaml ==="
        flutter pub deps
    
    - name: Quick build test
      run: |
        echo "=== Testing Flutter pub get ==="
        flutter pub get
        echo "=== Testing Flutter analyze ==="
        flutter analyze --no-fatal-infos || echo "Analysis completed with warnings"
        echo "=== Status check completed ==="
